application: hayate-vwr
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: 7d  # This is good for images, which never change

handlers:
- url: /static/.*(js|css)
  static_dir: static
  expiration: 2s # because these change rapidly in this stage
  
- url: /static
  static_dir: static
  
- url: /.*
  script: main.app
  secure: always
  
libraries:
- name: django
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

inbound_services:
- channel_presence