application: hayate
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static

- url: /index.html
  script: main.app

- url: /.*
  script: main.app
  
libraries:
- name: django
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
